### ISSUE TITLE
Recontructed output obtained for a Paris image is not as clear

### ISSUE THREAD

**Issue by harshithabk** [leehomyc/High-Res-Neural-Inpainting#38]
Hi, 

The final reconstructed output for a Paris test image as mentioned in the paper >https://arxiv.org/pdf/1611.09969v2.pdf

 is given below
![capture](https://user-images.githubusercontent.com/34910044/43683843-3ce80de8-98b2-11e8-8cf3-f79682112ade.JPG)     

However, the output that we received for the same test image is as below:
![result_0016](https://user-images.githubusercontent.com/34910044/43683856-82277998-98b2-11e8-9536-811b7666ebf3.png)   

I used the same models as mentioned :  https://drive.google.com/open?id=0BxYj-YwDqh45XzZVTXF1dnJXY28

Could you please let me know the reason for the same?

Also, i tested the source code for couple of images from ImageNet. That was also not reconstructed as expected.  
Please find the results as attached here:
![result_0026](https://user-images.githubusercontent.com/34910044/43683901-26c325b0-98b3-11e8-908c-f82cb92ff910.png)
![result_0027](https://user-images.githubusercontent.com/34910044/43683902-27056812-98b3-11e8-8e35-3f7dd900b199.png)
![result_0028](https://user-images.githubusercontent.com/34910044/43683903-2748639c-98b3-11e8-8b1d-6989e778f672.png)
![result_0024](https://user-images.githubusercontent.com/34910044/43683904-2791f64c-98b3-11e8-8747-106ba56c1c9c.png)

Kindly let me know your opinion on the same.

Thank you.

**Comment by leehomyc** [comment]
I did a bit of acceleration upon previous code. Basically, in each iteration, I fix the nearest neighbor so that I only need to search once during texture optimization. It may hurt a bit of the quality but the speed is much faster. I think what you showed make sense.

For other images, the final output is very much dependent on the initialization, i.e. the content network. If the content network does not give reasonable results, the final results are likely to fail. We've seen a lot of such cases in our experiments as well. That is a limitation of our approach and thanks for pointing out.

**Comment by harshithabk** [comment]
Thank you so much for the response.  
So, if I train it with new dataset, may be consider human face dataset, it would not be reconstructed completely is it?

**Comment by leehomyc** [comment]
It can, but the quality may be slightly worse than previous (slow) version. If you wanna try the slower version you can use the legacy code here:

https://github.com/leehomyc/Faster-High-Res-Neural-Inpainting/tree/3f8d332ed8b6f04d809eb1b9b6fa9472888dd163

**Comment by harshithabk** [comment]
Okay, Thanks a lot for the information & your timely support.
That was helpful.
